# This file was generated by GoReleaser. DO NOT EDIT.
cask "tq" do
  version "0.21.36"

  on_macos do
    on_intel do
      sha256 "63a372913c68d9d4993bd8b9278956d8cbbc45c301a1c13314389fe26ec67d96"
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "25e92823a1168898cafb11222262dc5886933802fdf24a8c7c9795aade9eaf24"
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "6470a59f89f31d0e5e472f17c8edcf641830c84384c0f65aac7fa1035d95b712"
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b1e804016de86521529d1ad8f5496cc23efbdd4a48140b11b10eb1cb0884432"
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tq"
  desc "Job-queue based orchestration system for Claude Code"
  homepage "https://github.com/MH4GF/tq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tq"

  # No zap stanza required

end
