# This file was generated by GoReleaser. DO NOT EDIT.
cask "tq" do
  version "0.21.32"

  on_macos do
    on_intel do
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_darwin_amd64.zip"
      sha256 "fe07cd4e653516d38ebc1a139a4909dcee2d2af77e3c4884febd951992ed0dbc"
    end
    on_arm do
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_darwin_arm64.zip"
      sha256 "a67ddaea86a38cb40294301fbab5dc128c29ebda29d001a53bf415c750e08e9b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_linux_amd64.tar.gz"
      sha256 "7155d007449dee8474d9998e4fc04cbdf1108d5cb57facc12cdc8f7a62876a61"
    end
    on_arm do
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_linux_arm64.tar.gz"
      sha256 "8440a2d877e2482f67ff82b5e77f3983416ea216d594a6c283c8e1b801325701"
    end
  end

  name "tq"
  desc "Job-queue based orchestration system for Claude Code"
  homepage "https://github.com/MH4GF/tq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tq"

  # No zap stanza required

end
