# This file was generated by GoReleaser. DO NOT EDIT.
cask "tq" do
  version "0.21.13"

  on_macos do
    on_intel do
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_darwin_amd64.zip"
      sha256 "df484a6987f93db4e984a7cabe61e7d1c22decc77be0f9ce8f9cc79de4199fdc"
    end
    on_arm do
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_darwin_arm64.zip"
      sha256 "0174380f54a43d57045c48eb4b1ecdd6425107681ee4444f10dc46dfb6b298c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_linux_amd64.tar.gz"
      sha256 "05c79326fc417b5ce0e6856a0de9c64d8371634ffd213d86f06d4a5e8ed2d32f"
    end
    on_arm do
      url "https://github.com/MH4GF/tq/releases/download/v#{version}/tq_#{version}_linux_arm64.tar.gz"
      sha256 "a96a19a13cf9e133b5045f9f3bbfdab2da865a5498ae314df7e4da270a20efa9"
    end
  end

  name "tq"
  desc "Job-queue based orchestration system for Claude Code"
  homepage "https://github.com/MH4GF/tq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tq"

  # No zap stanza required

end
